/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Cascader: typeof import('./src/components/cascader/index.vue')['default']
    Codeinput: typeof import('./src/components/codeinput/index.vue')['default']
    Countdown: typeof import('./src/components/countdown/index.vue')['default']
    Descriptions: typeof import('./src/components/descriptions/index.vue')['default']
    HeadOperation: typeof import('./src/components/headOperation/index.vue')['default']
    Language: typeof import('./src/components/Language/index.vue')['default']
    Modal: typeof import('./src/components/modal/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDynamicTags: typeof import('naive-ui')['NDynamicTags']
    NIcon: typeof import('naive-ui')['NIcon']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTooltip: typeof import('naive-ui')['NTooltip']
    Paging: typeof import('./src/components/paging/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Terminal: typeof import('./src/components/terminal/index.vue')['default']
    VerifyModal: typeof import('./src/components/modal/timeout/verifyModal.vue')['default']
  }
}
